const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const appSource = fs.readFileSync(path.join(root, "scene-planner-prototype", "app.js"), "utf8");
const adapterSource = fs.readFileSync(path.join(root, "scene-planner-prototype", "designer-adapter.js"), "utf8");
const indexSource = fs.readFileSync(path.join(root, "scene-planner-prototype", "index.html"), "utf8");

class ElementStub {
  constructor(value = "") { this.value = value; this.hidden = false; this.checked = false; this.disabled = false; this.textContent = ""; this.children = []; this._listeners = {}; this.dataset = {}; this.style = {}; this.className = ""; this.widthWrites = 0; this.heightWrites = 0; this._width = 0; this._height = 0; Object.defineProperty(this, "width", { get: () => this._width, set: next => { this._width = next; this.widthWrites += 1; } }); Object.defineProperty(this, "height", { get: () => this._height, set: next => { this._height = next; this.heightWrites += 1; } }); this.classList = { add: (...names) => { this.className += ` ${names.join(" ")}`; } }; }
  addEventListener(name, handler) { this._listeners[name] = handler; }
  append(...nodes) { this.children.push(...nodes); }
  replaceChildren(...nodes) { this.children = nodes; }
  querySelector() { return new ElementStub(); }
  click() { this._listeners.click?.({ preventDefault() {}, stopPropagation() {} }); }
  setAttribute() {}
  setPointerCapture() {}
  releasePointerCapture() {}
  hasPointerCapture() { return false; }
  getBoundingClientRect() { return { width: 1200, height: 800, left: 0, top: 0 }; }
  getContext() { return new Proxy({}, { get: (target, property) => target[property] || (() => {}), set: (target, property, value) => { target[property] = value; return true; } }); }
}

function createHarness(saved, storageKey = "disguise-scene-generator-state-v5") {
  const initialValues = { "#room-width": "20", "#room-depth": "12", "#stage-width": "12", "#stage-depth": "8", "#stage-height": "0.8", "#measure-from-stage": "", "#snap-mode": "grid-1" };
  const elements = new Map(); const elementFor = selector => { if (!elements.has(selector)) elements.set(selector, new ElementStub(initialValues[selector] || "")); return elements.get(selector); };
  const updateMode = new ElementStub("update"); updateMode.checked = true; const cleanMode = new ElementStub("clean"); const storage = new Map(); if (saved) storage.set(storageKey, JSON.stringify(saved));
  const document = { querySelector(selector) { if (selector === "input[name=sync-mode]:checked") return updateMode.checked ? updateMode : cleanMode; return elementFor(selector); }, querySelectorAll(selector) { if (selector === "input[name=sync-mode]") return [updateMode, cleanMode]; if (selector === "#standard-checklist input:checked") return []; return []; }, createElement() { return new ElementStub(); }, createTextNode(text) { return new ElementStub(text); } };
  const context = { console, document, location: { hostname: "127.0.0.1", port: "4173", origin: "http://127.0.0.1:4173" }, localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value) }, crypto: { randomUUID: () => `test-${storage.size}-${Math.random()}` }, Blob: class {}, URL: { createObjectURL: () => "blob:test", revokeObjectURL() {} }, addEventListener() {}, confirm: () => false, setTimeout, clearTimeout };
  context.window = context; context.globalThis = context; vm.createContext(context); vm.runInContext(appSource, context, { filename: "app.js" }); context.scenePlannerDebug.__elements = elements; return context.scenePlannerDebug;
}

function sceneObject(type, pluginId, position = { x: 1, y: 2, z: 3 }) {
  const object = { id: 1, pluginId, type, name: `${type} test`, transform: { position, rotation: { x: 10, y: 20, z: 30 } } };
  if (["screen", "surface"].includes(type)) { object.geometry = { width: 4, height: 2 }; object.transform.rotation.x = 0; object.transform.rotation.z = 0; }
  if (type === "projector") object.lookAt = { x: 0, y: 0.8, z: 0 };
  if (["screen", "surface", "projector"].includes(type)) object.media = { resolutionX: 1920, resolutionY: 1200, ...(type === "screen" ? { pixelsPerInch: 10 } : {}) };
  return object;
}
function resultFor(payload, id = "designer-id") { return { designerId: id, path: `objects/test/${id}.apx`, readback: JSON.parse(JSON.stringify({ transform: payload.transform, ...(payload.lookAt ? { lookAt: payload.lookAt } : {}), ...(payload.geometry ? { geometry: payload.geometry } : {}) })) }; }

(async () => {
  const core = createHarness();
  assert.equal(core.state.objects.length, 0); assert.equal(core.state.stage.enabled, true); assert.equal(core.newObject("projector").transform.position.y, 2.5); assert.equal(core.newObject("screen").transform.position.y, 0); assert.equal(core.newObject("projector").lookAt.y, 0); assert.equal(core.newObject("screen").media.pixelsPerInch, 10); assert.equal("pixelsPerInch" in core.newObject("surface").media, false); assert.equal(core.newObject("dmxScreen").geometry.width, 4); assert.equal(core.newObject("dmxLight").transform.position.y, 3);
  const screen = sceneObject("screen", "plugin-screen", { x: 3, y: 0, z: -5 }); const payload = core.objectPayload(screen); assert.equal(core.finite("1,5", 9), 1.5); assert.equal(core.finite("", 9), 9); assert.equal(core.formatValue(4), "4"); assert.equal(core.formatValue(1.5), "1,5");
  assert.deepEqual(JSON.parse(JSON.stringify(payload)), { pluginId: "plugin-screen", type: "screen", name: "screen test", transform: { position: { x: 3, y: 0, z: -5 }, rotation: { x: 0, y: 20, z: 0 } }, geometry: { width: 4, height: 2 }, media: { resolutionX: 1920, resolutionY: 1200, pixelsPerInch: 10 } }); assert.equal(core.validateReadback(payload, resultFor(payload)), true); assert.throws(() => core.validateReadback(payload, { readback: { transform: { position: { x: 3, y: .0001, z: -5 }, rotation: { x: 0, y: 20, z: 0 } }, geometry: { width: 4, height: 2 } } }), /не пройдена/);
  assert.match(adapterSource, /assign\("offset", Vec\(pos\["x"\], pos\["y"\] \+ geometry\["height"\] \/ 2\.0, pos\["z"\]\)/); assert.match(adapterSource, /assign\("scale", Vec\(geometry\["width"\], geometry\["height"\], 0\.1\)\)/); assert.match(adapterSource, /assign\("configPosition", position_value\)/); assert.match(adapterSource, /assign\("configLookAt"/); assert.match(adapterSource, /config_rotation = getattr\(obj, "configRotation"/); assert.match(adapterSource, /stage\.children/); assert.match(adapterSource, /stageId/); assert.match(adapterSource, /scene_path = "objects\/object\/dsg-scene-cube\.apx"/); assert.match(adapterSource, /LookAtManipulable/); assert.match(adapterSource, /needsMesh/); assert.match(adapterSource, /DmxScreen/); assert.match(adapterSource, /FixtureGroup/); assert.match(adapterSource, /dmxScreens/); assert.match(adapterSource, /dmxLights/); assert.match(adapterSource, /resourcePath\(payload\)/); assert.match(adapterSource, /desired_path = folder/); assert.match(adapterSource, /resourceManager\.remove\(resource_path\)/); assert.match(adapterSource, /deleteManagedScript/); assert.match(adapterSource, /liveUpdate: true/); assert.match(adapterSource, /LIVE_PATH = "\/api\/session\/liveupdate"/); assert.match(adapterSource, /sourcePath = String\(record\?\.path/); assert.match(adapterSource, /BigInt\(String\(designerId\)/); assert.match(adapterSource, /getByUID\(0x\$\{uid\.toString\(16\)\}\)/); assert.match(adapterSource, /subscribe: \{ object, properties \}/); assert.match(adapterSource, /const collections = \["ledScreens", "dmxScreens", "dmxLights", "surfaces", "projectors", "cameras"\]/); assert.match(adapterSource, /set: changes/); assert.match(adapterSource, /binding\.initialized/); assert.match(adapterSource, /binding\.value = change\.value/); assert.match(adapterSource, /liveResetSubscriptionIds/); assert.match(adapterSource, /resubscribing/); assert.match(adapterSource, /liveLog\("subscribed"/); assert.match(adapterSource, /pluginId: binding\?\.pluginId/); assert.doesNotMatch(adapterSource, /field === "transform\.position\.y" && \["screen", "surface"\]/); assert.match(adapterSource, /add\("transform\.position\.y", "object\.offset\.y", value => Number\(value\) \+ Number\(payload\.geometry\?\.height \|\| 0\) \/ 2/); assert.match(adapterSource, /getLiveLogs/); assert.doesNotMatch(adapterSource, /stage\.floor_size\s*=/); assert.doesNotMatch(adapterSource, /posRelativeOrGlobal/); assert.doesNotMatch(adapterSource, /rotRelativeOrGlobal/); assert.doesNotMatch(adapterSource, /triangle\.a\s*=/); assert.doesNotMatch(adapterSource, /triangle\.b\s*=/); assert.doesNotMatch(adapterSource, /triangle\.c\s*=/); assert.match(adapterSource, /typeClasses = .*camera: "Camera"/);
  assert.match(indexSource, /id="stage-enabled"/); assert.match(indexSource, /id="stage-center-x"/); assert.match(indexSource, /id="stage-center-z"/); assert.ok(indexSource.indexOf('id="stage-width"') < indexSource.indexOf('id="stage-center-x"')); assert.match(indexSource, /id="diff-missing"/); assert.match(indexSource, /id="live-toggle" type="checkbox"/); assert.doesNotMatch(indexSource, /id="live-toggle" type="checkbox" disabled/); assert.match(indexSource, /id="objects-toggle"/); assert.match(indexSource, /id="clear-scene-button"/); assert.match(indexSource, /id="live-log-button"/); assert.match(indexSource, /data-create-type="dmxScreen"/); assert.match(indexSource, /data-create-type="dmxLight"/); assert.match(indexSource, /app\.js\?v=10\.24/); assert.match(indexSource, /app-version.*v10\.24/); assert.doesNotMatch(indexSource, /data-add-type=/); assert.doesNotMatch(indexSource, /id="reset-button"/);
  assert.deepEqual(JSON.parse(JSON.stringify(core.fieldSections(core.newObject("camera")).map(section => section.fields?.map(field => field[1]) || []))), [["transform.position.x", "transform.position.z", "transform.position.y"], ["transform.rotation.y"]]);
  assert.equal(core.nextDimensionField(core.newObject("screen"), "geometry.width"), "geometry.height"); assert.equal(core.nextDimensionField(core.newObject("screen"), "geometry.height"), "transform.position.y"); assert.equal(core.nextDimensionField(core.newObject("screen"), "transform.position.y"), null); assert.equal(core.nextDimensionField(core.newObject("projector"), "geometry.width"), null);
  assert.match(appSource, /pending: true/); assert.match(appSource, /distance < 4/); assert.match(appSource, /ctrlKey[\s\S]*duplicateObject/); assert.match(appSource, /focusActiveField\(nextPath\)/); assert.match(appSource, /activeFieldRefs\.set\(path, input\)/); assert.match(appSource, /ensureLiveObjects/); assert.match(appSource, /scheduleLiveSceneImport/); assert.match(appSource, /deleteManagedObjects/); assert.match(appSource, /STANDALONE_PREVIEW/); assert.doesNotMatch(appSource, /liveValueQueue/); assert.doesNotMatch(appSource, /livePendingValues/);
  const heightHarness = createHarness(); const heightScreen = heightHarness.newObject("screen"); heightHarness.state.stage = { enabled: true, centerX: 0, centerZ: 0, floorY: 1, width: 12, depth: 8, height: 1, measureFromStage: true }; heightScreen.transform.position.y = 1; assert.equal(heightHarness.objectHeightValue(heightScreen), 0); heightHarness.setObjectHeight(heightScreen, -3); assert.equal(heightScreen.transform.position.y, -2); assert.equal(heightHarness.objectHeightValue(heightScreen), -3); heightHarness.state.stage.measureFromStage = false; heightHarness.setObjectHeight(heightScreen, -3); assert.equal(heightScreen.transform.position.y, -3);
  const migrated = createHarness({ version: 5, room: { width: 20, depth: 12 }, stage: { centerX: 3, centerZ: -2, floorY: 1.1, width: 10, depth: 6, height: 0.6 }, nextId: 2, objects: [{ id: 1, pluginId: "old-screen", type: "screen", name: "Old", transform: { position: { x: 4, y: 1.5, z: -2 }, rotation: { x: 7, y: 35, z: 9 } }, geometry: { width: 4, height: 2 } }] }); assert.equal(migrated.state.stage.enabled, true); assert.equal(migrated.state.stage.floorY, .5);
  core.state.room = { width: 20, depth: 12 }; core.state.stage = { enabled: true, centerX: 10, centerZ: -5, floorY: .8, width: 12, depth: 8, height: .8, measureFromStage: false }; const frame = { left: 100, top: 50, scale: 10 }; assert.deepEqual(JSON.parse(JSON.stringify(core.toScreen(10, -5, frame))), { x: 300, y: 160 }); assert.deepEqual(JSON.parse(JSON.stringify(core.stageBounds())), { minX: 4, maxX: 16, minZ: -9, maxZ: -1 }); core.state.stage.enabled = false; assert.deepEqual(JSON.parse(JSON.stringify(core.stageBounds())), { minX: -10, maxX: 10, minZ: -6, maxZ: 6 });
  const schema = JSON.parse(fs.readFileSync(path.join(root, "schemas", "scene.schema.json"), "utf8")); assert.equal(schema.properties.stage.properties.enabled.type, "boolean"); assert.ok(schema.$defs.sceneObject.properties.type.enum.includes("designer"));
  core.state.room = { width: 20, depth: 12 }; core.state.stage.enabled = true; core.state.objects = [sceneObject("screen", "hit-screen", { x: 0, y: 0, z: 0 })]; assert.equal(core.hitTest(600, 400).pluginId, "hit-screen"); assert.equal(core.hitTest(600, 410), undefined);
  core.state.objects = [];
  const inspection = { objects: [{ id: "uid-1", type: "projector", path: "objects/projector/dsg-p-1.apx", description: "Front projector", transform: { position: { x: 3, y: 2.5, z: -5 }, rotation: { x: 12, y: 34, z: 56 } }, lookAt: { x: 0, y: 1, z: 0 }, className: "Projector", collection: "projectors", managed: true, pluginId: "p-1" }, { id: "uid-2", type: "designer", path: "objects/prop/manual.apx", description: "Manual prop", transform: { position: { x: 1, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 } }, className: "Prop", collection: "children" }], floorY: 0, floorPosition: { x: 0, y: 0, z: 0 }, roomFloor: { width: 24, depth: 14 }, sceneCube: { designerId: "cube", path: "objects/object/dsg-scene-cube.apx" } };
  await core.importDesignerScene({ inspectScene: async () => inspection }); assert.equal(core.state.objects.length, 2); assert.equal(core.state.objects[0].name, "Front projector"); assert.equal(core.state.objects[0].transform.rotation.z, 56); assert.equal(core.state.objects[1].type, "designer"); assert.equal(core.state.room.width, 24); assert.equal(core.state.sync.sceneCube.designerId, "cube"); assert.equal(core.state.stage.enabled, true);
  const noCubeHarness = createHarness({ version: 5, room: { width: 20, depth: 12 }, stage: { enabled: true, centerX: 0, centerZ: 0, floorY: 0, width: 12, depth: 8, height: 0.8 }, objects: [sceneObject("screen", "local-only")] }); await noCubeHarness.importDesignerScene({ inspectScene: async () => ({ objects: [], floorY: 0, roomFloor: { width: 20, depth: 12 }, sceneCube: null }) }); assert.equal(noCubeHarness.state.objects.length, 0); assert.equal(noCubeHarness.state.stage.enabled, false);
  const current = sceneObject("screen", "managed-screen", { x: 1, y: 1.5, z: 3 }); const previousPayload = core.objectPayload(current); previousPayload.transform.position.y = 0; core.state.objects = [current]; core.state.sync.objects = { "managed-screen": { designerId: "managed-uid", lastExported: "old", payload: previousPayload } }; const managedInspection = { objects: [{ id: "managed-uid", type: "screen", path: "objects/ledscreen/dsg-managed-screen.apx", managed: true }], floorY: 0 }; const diff = await core.makeDiff({ inspectScene: async () => managedInspection }, "update"); assert.deepEqual(JSON.parse(JSON.stringify(diff.update[0].changed)), { name: "screen test", transform: { position: { y: 1.5 } } });
  const missingDiff = await core.makeDiff({ inspectScene: async () => ({ objects: [], floorY: 0 }) }, "update"); assert.equal(missingDiff.create.length, 0); assert.equal(missingDiff.missing.length, 1);
  const nameHarness = createHarness(); nameHarness.state.objects = [nameHarness.newObject("screen"), nameHarness.newObject("screen")]; nameHarness.state.objects[0].name = "LED Screen 2"; nameHarness.state.objects[1].name = "LED Screen 3"; assert.equal(nameHarness.newObject("screen").name, "LED Screen 4");
  console.log("scene-planner v10 tests: ok");
})().catch(error => { console.error(error); process.exitCode = 1; });
